#!/bin/bash
[ -z "$MIX_ENV" ] && MIX_ENV=dev
n='rockside'
m='Rockside.Sanity'

while [ -n "$1" ]; do
    if   [ "$1" = "-n" -a -n "$2" ]; then n=$2; shift; shift
    else m=$1; shift
    fi
done
echo "Running Rockside with module $m" >&2
exec elixir --sname $n -pa _build/$MIX_ENV/consolidated \
    -S mix run --no-halt --eval \
    "Rockside.run($m)"

# instead of this script, rather make a runner via: mix server [opts]
# see: http://git.io/7aHdIw
