#!/bin/bash
n='rockside'
m='Rockside.Sanity'

while [ -n "$1" ]; do
    if   [ "$1" = "-n" -a -n "$2" ]; then n=$2; shift; shift
    else m=$1; shift
    fi
done
echo "Running Rockside with module $m" >&2
exec elixir --sname $n -S mix run --no-halt --eval \
    "Rockside.run($m)"
